#!/usr/bin/env python3
"""
Generate Patches/Buildings_MoreCoverage.xml from tools/assignments.tsv.

Emits one ArgonicCore PatchOperationDistributeCost per (building, metal), using
Expanded Materials - Metals' own Steel-base parameters, so the ops are shaped
exactly like EMM's own patches.

EMM-derived Steel-base parameters (percentage / extraCostFactor), read off EMM's
DistributeCost ops that source each metal from Steel (Silver for StainlessSteel,
which has no Steel-base building precedent):

    Titanium        100% / 0.80     structural / heavy machinery / turret frames
    Copper          100% / 1.75     thermal / heat-exchange  (factor tracks copper's ~2x mining yield)
    StainlessSteel  100% / 0.75     food / medical / plumbing bodies
    Lead             80% / 1.25     nuclear shielding

Silicon/Germanium are NOT emitted: EMM sources them only from Gold (a high-tech
electronics cost), and the modded electronics here carry Components, not Gold.
Components are functional parts, not a raw-material substitute -- see README.

When several metals draw from one building's Steel, they are emitted in
body -> thermal -> shield order and each takes 50% (sequential, matching EMM's
own multi-metal ShipHeatsink treatment) so later ops are not starved.
"""
import os
import re
import sys

# metal -> (solo percentage, extraCostFactor), EMM Steel-base medians
PARAM = {
    "EM_Titanium":       (100, 0.8),
    "EM_Copper":         (100, 1.75),
    "EM_StainlessSteel": (100, 0.75),
    "EM_Lead":           (80,  1.25),
}
ORDER = {"EM_Titanium": 0, "EM_StainlessSteel": 0, "EM_Copper": 1, "EM_Lead": 2}
SHARED_PCT = 50  # each metal's share when >1 metal draws from the same Steel cost

HERE = os.path.dirname(os.path.abspath(__file__))
ASSIGN = os.path.join(HERE, "assignments.tsv")
OUT = os.path.join(HERE, "..", "Patches", "Buildings_MoreCoverage.xml")


def load():
    builds = []
    with open(ASSIGN, encoding="utf-8") as fh:
        for line in fh.read().splitlines()[1:]:
            p = line.split("\t")
            if len(p) < 5:
                continue
            metals = [m for m in re.findall(r"EM_\w+", p[4]) if m in PARAM]
            if not metals:
                continue
            metals = sorted(set(metals), key=lambda m: ORDER.get(m, 9))
            builds.append((p[1], metals))
    return builds


def op(defname, metal, pct, factor):
    return (
        '      <li Class="ArgonicCore.PatchOperations.PatchOperationDistributeCost">\n'
        "        <success>Always</success>\n"
        f'        <xpath>/Defs/ThingDef[defName="{defname}"]/costList/Steel</xpath>\n'
        f"        <newMaterial>{metal}</newMaterial>\n"
        f"        <percentage>{pct}</percentage>\n"
        f"        <extraCostFactor>{factor}</extraCostFactor>\n"
        "      </li>"
    )


def main():
    builds = load()
    ops = []
    for defname, metals in builds:
        for m in metals:
            solo_pct, factor = PARAM[m]
            pct = solo_pct if len(metals) == 1 else SHARED_PCT
            ops.append(op(defname, m, pct, factor))
    body = "\n".join(ops)
    xml = (
        '<?xml version="1.0" encoding="utf-8" ?>\n<!--\n'
        "  More Mod Patches for Expanded Materials - Metals.\n"
        "  DO NOT EDIT - generated by tools/generate.py from tools/assignments.tsv.\n"
        "  Extends EMM's DistributeCost treatment to modded Steel-costing buildings EMM does not curate,\n"
        "  using EMM's own Steel-base parameters. Every op has success=Always so an absent def cannot\n"
        "  abort the sequence. Load after Expanded Materials - Metals.\n-->\n"
        "<Patch>\n  <Operation Class=\"PatchOperationFindMod\">\n    <mods>\n"
        "      <li>Expanded Materials - Metals</li>\n    </mods>\n"
        '    <match Class="PatchOperationSequence">\n      <success>Always</success>\n      <operations>\n'
        + body
        + "\n      </operations>\n    </match>\n  </Operation>\n</Patch>\n"
    )
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(xml)
    print(f"wrote {len(ops)} ops across {len(builds)} buildings -> {os.path.normpath(OUT)}")


if __name__ == "__main__":
    sys.exit(main())
